import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
        <Toaster
          position="top-right"
          duration={2500}
          toastOptions={{
            className: {
              error: "error-toast",
              success: "success-toast",
            },
          }}
        />
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
